import type { Metadata } from "next";
import { Geist, Roboto, Roboto_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/providers";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const roboto = Roboto_Mono({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dmSans.variable} ${roboto.variable} antialiased font-sans`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
